"""Project state.db into the Planning-with-Files layout.

Planning-with-Files (OthmanAdi/planning-with-files) keeps an agent's plan on
disk so it survives /clear, compaction, and crashes: `task_plan.md` with phase
checkboxes, `findings.md` for decisions, `progress.md` for the session log,
under `.planning/<slug>/`.

These files are regenerated from the database, never hand-edited -- with 97
units, a hand-maintained checklist drifts from reality within an hour, and a
plan that disagrees with the state is worse than no plan. Edit state via the
`mig` CLI; re-run `mig plan` to refresh the markdown.
"""
from __future__ import annotations

import os
import time
from collections import defaultdict

from . import db, units as units_mod, validate

STATUS_BOX = {
    "complete": "x", "validated": "x", "failed": "!", "blocked": "!",
    "generated": "~", "planned": "~", "pending": " ",
}


def planning_dir(run_dir, slug=None):
    slug = slug or time.strftime("%Y-%m-%d-alteryx-sdp")
    return os.path.join(run_dir, ".planning", slug)


def write(con, run_dir, slug=None):
    out = planning_dir(run_dir, slug)
    os.makedirs(out, exist_ok=True)

    wf = db.get_meta(con, "workflow_path", "(unset)")
    rows = [dict(r) for r in con.execute("SELECT * FROM units ORDER BY seq")]
    counts = defaultdict(int)
    for r in rows:
        counts[r["status"]] += 1
    total_tools = con.execute("SELECT count(*) c FROM nodes").fetchone()["c"]
    done = counts["complete"] + counts["validated"]

    deps = defaultdict(list)
    for r in con.execute("SELECT unit_id, depends_on FROM unit_deps ORDER BY 1,2"):
        deps[r["unit_id"]].append(r["depends_on"])

    # ---------------- task_plan.md ----------------
    L = ["# Task plan -- Alteryx to Databricks SDP", "",
         "Source workflow: `%s`" % wf,
         "Run directory: `%s`" % os.path.abspath(run_dir), "",
         "**Generated from `state.db`. Do not hand-edit -- run `mig plan` to refresh.**", "",
         "Progress: **%d / %d units complete** (%d tools total)" % (done, len(rows), total_tools),
         ""]

    L += ["## Phase 1 -- Extract (once)", ""]
    lb = db.get_meta_json(con, "lakebridge_run")
    L.append("- [%s] Lakebridge analyzer run%s" % (
        "x" if lb else " ", " -- %s" % lb.get("startTime") if lb else ""))
    L.append("- [%s] Workflow XML parsed to state.db (%d tools, %d connections)" % (
        "x" if total_tools else " ", total_tools,
        con.execute("SELECT count(*) c FROM edges").fetchone()["c"]))
    L.append("- [%s] Units built (%d units, %d unique after de-duplication)" % (
        "x" if rows else " ", len(rows),
        sum(1 for r in rows if not r["dedupe_of"])))
    L.append("")

    L += ["## Phase 2 -- Resolve gaps", ""]
    for g in con.execute(
            "SELECT gap_id,kind,blocking,status,question FROM gaps ORDER BY blocking DESC, gap_id"):
        L.append("- [%s] #%d (%s%s) %s" % (
            "x" if g["status"] != "open" else " ", g["gap_id"], g["kind"],
            ", blocking" if g["blocking"] else "", g["question"][:200]))
    if not con.execute("SELECT 1 FROM gaps LIMIT 1").fetchone():
        L.append("- [x] No gaps recorded")
    L.append("")

    L += ["## Phase 3 -- Migrate units (dependency order)", ""]
    for r in rows:
        box = STATUS_BOX.get(r["status"], " ")
        tail = []
        if r["dedupe_of"]:
            tail.append("duplicate of %s -- reuse, do not regenerate" % r["dedupe_of"])
        if deps[r["unit_id"]]:
            tail.append("after %s" % ", ".join(deps[r["unit_id"]]))
        if r["layer"]:
            tail.append(r["layer"])
        L.append("- [%s] **%s** %s (%d tools)%s" % (
            box, r["unit_id"], r["title"], r["tool_count"],
            " -- " + "; ".join(tail) if tail else ""))
    L.append("")

    L += ["## Phase 4 -- Validate", ""]
    s = validate.summary(con)
    for level in ("structural", "semantic", "code", "data"):
        st = s.get(level)
        if not st:
            L.append("- [ ] %s validation not run" % level)
        else:
            ok = st.get("fail", 0) == 0
            L.append("- [%s] %s: %d pass, %d fail, %d skip" % (
                "x" if ok else "!", level, st.get("pass", 0), st.get("fail", 0), st.get("skip", 0)))
    L.append("")
    L.append("## Resume")
    L.append("")
    L.append("After a context reset, run `mig status` then `mig next` -- the database, "
             "not this file, is the source of truth.")
    _w(os.path.join(out, "task_plan.md"), L)

    # ---------------- findings.md ----------------
    F = ["# Findings -- decisions, gaps, and hazards", "",
         "Appended by `mig decide` / `mig gap`. Regenerated by `mig plan`.", ""]
    F += ["## Decision log", ""]
    any_dec = False
    for d in con.execute(
            "SELECT unit_id,node_key,basis,summary,detail,confidence FROM decisions "
            "ORDER BY decision_id"):
        any_dec = True
        F.append("- **%s** [%s%s]%s %s" % (
            d["unit_id"] or "global", d["basis"],
            "/" + d["confidence"] if d["confidence"] else "",
            " `%s`" % d["node_key"] if d["node_key"] else "", d["summary"]))
        if d["detail"]:
            F.append("  - %s" % d["detail"])
    if not any_dec:
        F.append("_No decisions recorded yet._")
    F.append("")

    F += ["## Gap register", ""]
    F.append("| # | unit | kind | blocking | status | question | resolution |")
    F.append("|---|------|------|----------|--------|----------|------------|")
    for g in con.execute("SELECT * FROM gaps ORDER BY blocking DESC, gap_id"):
        F.append("| %d | %s | %s | %s | %s | %s | %s |" % (
            g["gap_id"], g["unit_id"] or (g["node_key"] or "-"), g["kind"],
            "yes" if g["blocking"] else "no", g["status"],
            (g["question"] or "").replace("|", "/")[:180],
            (g["resolution"] or "").replace("|", "/")[:120]))
    F.append("")

    F += ["## Determinism and portability hazards", ""]
    for h in con.execute(
            "SELECT kind, count(*) c FROM hazards GROUP BY 1 ORDER BY c DESC"):
        F.append("- `%s` -- %d occurrence(s)" % (h["kind"], h["c"]))
    F.append("")
    _w(os.path.join(out, "findings.md"), F)

    # ---------------- progress.md ----------------
    P = ["# Progress log", "",
         "Last refreshed: %s" % time.strftime("%Y-%m-%d %H:%M:%S"), "",
         "## Unit status", ""]
    for status in ("complete", "validated", "failed", "blocked", "generated", "planned", "pending"):
        n = counts.get(status, 0)
        if n:
            P.append("- %s: %d" % (status, n))
    P.append("")
    P.append("## Validation results")
    P.append("")
    fails = validate.failures(con)
    if not fails:
        P.append("No failing checks recorded.")
    else:
        P.append("| unit | level | check | detail |")
        P.append("|------|-------|-------|--------|")
        for f in fails[:100]:
            P.append("| %s | %s | %s | %s |" % (
                f["unit_id"] or "-", f["level"], f["check_name"],
                (f["detail"] or "").replace("|", "/")[:160]))
    P.append("")
    P.append("## Artifacts")
    P.append("")
    arts = list(con.execute("SELECT unit_id,path,role FROM artifacts ORDER BY unit_id"))
    if not arts:
        P.append("_None recorded yet._")
    for a in arts:
        P.append("- %s (%s) -> `%s`" % (a["unit_id"], a["role"], a["path"]))
    P.append("")
    P.append("## Next ready units")
    P.append("")
    for u in units_mod.ready(con, limit=8):
        P.append("- %s %s (%d tools)" % (u["unit_id"], u["title"], u["tool_count"]))
    _w(os.path.join(out, "progress.md"), P)

    # Pointer file, so a parallel run can select this plan.
    with open(os.path.join(run_dir, ".active_plan"), "w", encoding="utf-8") as fh:
        fh.write(os.path.relpath(out, run_dir).replace("\\", "/"))

    return {"dir": out, "files": ["task_plan.md", "findings.md", "progress.md"],
            "units": len(rows), "complete": done}


def _w(path, lines):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
